"use client";

import { useEffect, useState, use } from "react";
import { useRouter } from "next/navigation";

export default function ExportIEPPage({ params }: { params: Promise<{ iepId: string }> }) {
  const { iepId } = use(params);
  const router = useRouter();
  const [iep, setIep] = useState<any>(null);
  const [exporting, setExporting] = useState(false);

  useEffect(() => {
    fetchIep();
  }, []);

  const fetchIep = async () => {
    const res = await fetch(`/api/iep/${iepId}`);
    const data = await res.json();
    setIep(data);
  };

  const exportPDF = async () => {
    setExporting(true);
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("Individualized Education Program", pageWidth / 2, 18, { align: "center" });
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("EduFlow Learning Management System", pageWidth / 2, 30, { align: "center" });

    y = 55;
    doc.setTextColor(0, 0, 0);

    // Student Info
    doc.setFillColor(243, 244, 246);
    doc.rect(14, y - 6, pageWidth - 28, 28, "F");
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Student Information", 18, y + 2);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Name: ${iep?.student?.name}`, 18, y + 10);
    doc.text(`Email: ${iep?.student?.email}`, 18, y + 17);
    doc.text(`Teacher: ${iep?.teacher?.name}`, pageWidth / 2, y + 10);
    doc.text(`Date: ${new Date(iep?.createdAt).toLocaleDateString()}`, pageWidth / 2, y + 17);

    y += 38;

    // Review Date & Status
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(`Status: `, 18, y);
    doc.setFont("helvetica", "normal");
    doc.text(iep?.status, 35, y);
    doc.setFont("helvetica", "bold");
    doc.text(`Review Date: `, pageWidth / 2, y);
    doc.setFont("helvetica", "normal");
    doc.text(
      iep?.reviewDate ? new Date(iep.reviewDate).toLocaleDateString() : "Not set",
      pageWidth / 2 + 28,
      y
    );

    y += 12;

    // Sections
    const sections = [
      { title: "Strengths", content: iep?.strengths, color: [220, 252, 231] },
      { title: "Areas of Concern", content: iep?.areasOfConcern, color: [254, 243, 199] },
      { title: "Learning Goals", content: iep?.learningGoals, color: [219, 234, 254] },
      { title: "Interventions", content: iep?.interventions, color: [243, 232, 255] },
    ];

    sections.forEach(({ title, content, color }) => {
      if (y > 240) {
        doc.addPage();
        y = 20;
      }

      // Section header
      doc.setFillColor(color[0], color[1], color[2]);
      doc.rect(14, y - 5, pageWidth - 28, 10, "F");
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text(title, 18, y + 2);

      y += 12;

      // Section content
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(content || "Not specified", pageWidth - 36);
      doc.text(lines, 18, y);
      y += lines.length * 6 + 10;
    });

    // Parent Acknowledgement
    if (y > 220) { doc.addPage(); y = 20; }
    doc.setDrawColor(200, 200, 200);
    doc.line(14, y, pageWidth - 14, y);
    y += 10;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Parent/Guardian Acknowledgement", 18, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text("I have reviewed and acknowledged this Individualized Education Program.", 18, y);
    y += 20;
    doc.line(18, y, 100, y);
    doc.line(pageWidth / 2 + 10, y, pageWidth - 18, y);
    y += 6;
    doc.setFontSize(9);
    doc.text("Parent/Guardian Signature", 18, y);
    doc.text("Date", pageWidth / 2 + 10, y);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by EduFlow on ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );

    doc.save(`IEP-${iep?.student?.name}-${new Date().toLocaleDateString()}.pdf`);
    setExporting(false);
  };

  if (!iep) return <div className="p-8">Loading...</div>;

  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-3xl mx-auto">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold">IEP Preview</h1>
          <button onClick={() => router.back()} className="text-sm text-blue-600 hover:underline">
            Back
          </button>
        </div>

        {/* Preview Card */}
        <div className="bg-white rounded shadow p-8 mb-6">
          <div className="bg-blue-600 text-white p-6 rounded-lg mb-6 text-center">
            <h2 className="text-xl font-bold">Individualized Education Program</h2>
            <p className="text-blue-200 text-sm mt-1">EduFlow Learning Management System</p>
          </div>

          <div className="grid grid-cols-2 gap-4 mb-6 bg-gray-50 p-4 rounded">
            <div>
              <p className="text-xs text-gray-400">Student</p>
              <p className="font-semibold">{iep.student?.name}</p>
            </div>
            <div>
              <p className="text-xs text-gray-400">Teacher</p>
              <p className="font-semibold">{iep.teacher?.name}</p>
            </div>
            <div>
              <p className="text-xs text-gray-400">Status</p>
              <span className={`text-sm font-medium px-2 py-0.5 rounded ${
                iep.status === "FINAL" ? "bg-green-100 text-green-600" : "bg-yellow-100 text-yellow-600"
              }`}>{iep.status}</span>
            </div>
            <div>
              <p className="text-xs text-gray-400">Review Date</p>
              <p className="font-semibold">
                {iep.reviewDate ? new Date(iep.reviewDate).toLocaleDateString() : "Not set"}
              </p>
            </div>
          </div>

          {[
            { title: "Strengths", content: iep.strengths, color: "bg-green-50 border-green-200" },
            { title: "Areas of Concern", content: iep.areasOfConcern, color: "bg-yellow-50 border-yellow-200" },
            { title: "Learning Goals", content: iep.learningGoals, color: "bg-blue-50 border-blue-200" },
            { title: "Interventions", content: iep.interventions, color: "bg-purple-50 border-purple-200" },
          ].map(({ title, content, color }) => (
            <div key={title} className={`border rounded p-4 mb-4 ${color}`}>
              <h3 className="font-semibold text-sm mb-2">{title}</h3>
              <p className="text-sm text-gray-700 whitespace-pre-line">{content || "Not specified"}</p>
            </div>
          ))}

          <div className="border-t pt-4 mt-4">
            <p className="text-xs text-gray-400 text-center">
              Generated by EduFlow · {new Date().toLocaleDateString()}
            </p>
          </div>
        </div>

        <button
          onClick={exportPDF}
          disabled={exporting}
          className="w-full bg-blue-600 text-white py-3 rounded-lg text-sm font-semibold hover:bg-blue-700 disabled:opacity-50"
        >
          {exporting ? "Generating PDF..." : "📄 Download PDF"}
        </button>
      </div>
    </div>
  );
}